# Generated by Django 5.2.7 on 2025-10-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_stock_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scent_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
