# Generated by Django 5.2.7 on 2025-10-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_scent_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='scent_notes',
        ),
        migrations.AddField(
            model_name='product',
            name='scent_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
